ports:
  - port: 3000
    onOpen: open-preview

tasks:
  - init: npm install
    command: npm start
metadata:
  name: example
  links:
    - url: https://dashboard.example.com
      title: My Dashboard
      icon: dashboard
