apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Trading-Fixture-Ingestion-1
  description: The place to be, for great artists
  labels:
    example.com/custom: custom_label_value
    source: commit-2233
  annotations:
    example.com/service-discovery: artistweb
    newrelic.com/dashboard-guid: MjY2NjU3MnxWSVp8REFTSEJPQVJEfGRhOjQ0OTc1MA
    backstage.io/kubernetes-id: "eks01"
    kafka.apache.org/consumer-groups: unity-sit-new-msk-sit-new/be-trading

  tags:
    - java
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
    - url: https://gitlab.com/williamhillplc/platform-engineering/portal/platform-engineering-portal/-/commit/784f0ee2ccc65b63fefc32b77cf5a0fbf1bb372a 
      title: git source - Commit 784f0ee2
       
spec:
  type: service
  lifecycle: production
  owner: artist-relations-team
  system: public-websites
  source: commit-2233
