apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: auth-template
  title: Auth Template
  description: Create a website powered with Next.js
  tags:
    - recommended
    - react
spec:
  owner: web@example.com
  type: website
  parameters:
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            requestUserCredentials:
              secretsKey: USER_OAUTH_TOKEN
              additionalScopes:
                github:
                  - workflow:write
                gitlab:
                  - write_repository
                  - sudo
            allowedHosts:
              - github.com
              - gitlab.com
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./
        values:
          service_name: '{{ parameters.service_name }}'
          owner: '{{ parameters.owner }}'
          
    - id: publish
      name: Publish
      action: publish:gitlab
      # action: publish:github
      input:
        allowedHosts: ['github.com']
        description: 'This is ${{ parameters.component_id }}'
        repoUrl: ${{ parameters.repoUrl }}
        token: ${{ secrets.USER_OAUTH_TOKEN }}

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    remoteUrl: ${{ steps.publish.output.remoteUrl }}
    entityRef: ${{ steps.register.output.entityRef }}
