apiVersion: backstage.io/v1beta2
kind: Template
metadata:
  name: Options-demo-nodejs-standard
  title: Options Demo Node.js Service deployable to EKS
  description: Create a new Demo Node.js Service
  tags:
    - nodejs
    - helm
    - demo
spec:
  owner: cpe
  type: service
  parameters:
    - title: Configure Your Demo Node.js Service
      required:
        - service_name
        - owner
        - docker_namespace
      properties:
        service_name:
          title: Service Name
          type: string
          description: Unique service name. Eg random-nodejs-service
          ui:autofocus: true
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
        system:
          title: System
          type: string
          description: System of the component
          ui:field: OwnedEntityPicker
        dataClassification:
          title: Data Classification
          type: string
          description: AWS Tag - Defined by DAVE tagging
          ui:field: AWSTagPicker
        customDropDown:
          title: Customized Drop Down 1
          type: string
          description: This Drop Down can be used any how 
          ui:field: CustomEntityPicker
          ui:url: https://gitlab.com/mufaddalWH/express-app/-/raw/master/users.json
          ui:options:
            customOptions:
              - We
              - are
              - building
              - backstage  
        docker_namespace:
          title: Docker Registry Namespace
          description: Docker registry namespace that image will be uploaded to. Eg. cpe
          type: string
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - gitlab.com
    - title: Data classification
      required:
        - AWSTags
      properties:
        AWSTags:
          title: AWS Tag - Defined by DAVE tagging
          type: string
          ui:field: AWSTagPicker
          ui:options:
            tagAssigned:
              - HighlyConfidential
              - Confidential 
              - NonPublic
              - Public        
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./
        values:
          service_name: '{{ parameters.service_name }}'
          owner: '{{ parameters.owner }}'
          docker_namespace: '{{ parameters.docker_namespace }}'
    - id: publish
      name: Publish
      action: publish:gitlab
      input:
        allowedHosts: ['gitlab.com']
        description: 'A simple "Hello World" node.js application deployable to EKS'
        repoUrl: '{{ parameters.repoUrl }}'
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: '{{ steps.publish.output.repoContentsUrl }}'
        catalogInfoPath: '/catalog-info.yaml'
  output:
    remoteUrl: '{{ steps.publish.output.remoteUrl }}'
    entityRef: '{{ steps.register.output.entityRef }}'
