apiVersion: backstage.io/v1beta2
kind: Template
metadata:
  name: demo-nodejs-standard
  title: Demo Node.js Service deployable to EKS
  description: Create a new Demo Node.js Service
  tags:
    - nodejs
    - helm
    - demo
spec:
  owner: feature
  type: service
  parameters:
    - title: Configure Your Demo Node.js Service
      required:
        - service_name
        - owner
        - docker_namespace
      properties:
        service_name:
          title: Service Name
          type: string
          description: Unique service name. Eg random-nodejs-service
          ui:autofocus: true
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
        docker_namespace:
          title: Docker Registry Namespace
          description: Docker registry namespace that image will be uploaded to. Eg. cpe
          type: string
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - gitlab.com
 
